repos:
-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    - id: black
      name: Run Formatter
      files: ^src/    

-   repo: https://github.com/pycqa/flake8
    rev: '6.1.0'  # pick a git hash / tag to point to
    hooks:
    - id: flake8
      name: Run Code Quality
      files: ^src/     

-   repo: https://github.com/pycqa/isort
    rev: 5.13.2  # ou a vers√£o mais recente
    hooks:
    - id: isort
      name: Run Isort
      files: ^src/        